#!/usr/bin/env bash

composerDockerImage="composer:1.9.0";
cypressDockerImage="cypress/included:3.5.0";
nodeDockerImage="node:12.12.0";

# Reset
Reset="\033[0m"; # Text Reset

# Regular Colors
Black="\033[0;30m"; # Black
Red="\033[0;31m"; # Red
Green="\033[0;32m"; # Green
Yellow="\033[0;33m"; # Yellow
Blue="\033[0;34m"; # Blue
Purple="\033[0;35m"; # Purple
Cyan="\033[0;36m"; # Cyan
White="\033[0;37m"; # White

# Bold
BBlack="\033[1;30m"; # Black
BRed="\033[1;31m"; # Red
BGreen="\033[1;32m"; # Green
BYellow="\033[1;33m"; # Yellow
BBlue="\033[1;34m"; # Blue
BPurple="\033[1;35m"; # Purple
BCyan="\033[1;36m"; # Cyan
BWhite="\033[1;37m"; # White

cmd=${1};
allArgs=${@};
allArgsExceptFirst=${@:2};
secondArg=${2};

## If no command provided, list commands
if [[ -z "${cmd}" ]]; then
    valid=true;
    printf "${Green}The following commands are available:\n${Yellow}";
    printf "  ./dev up\n";
    printf "  ./dev down\n";
    printf "  ./dev provision\n";
    printf "  ./dev login [args]\n";
    printf "  ./dev cli [args]\n";
    printf "  ./dev yarn [args]\n";
    printf "  ./dev composer [args]\n";
    printf "  ./dev phpcs\n";
    printf "  ./dev psalm\n";
    printf "  ./dev phpstan\n";
    printf "  ./dev phpunit [args]\n";
    printf "  ./dev eslint\n";
    printf "  ./dev cypress\n";
    printf "  ./dev cypress-interactive${Reset}\n";
    exit 0;
fi

if [[ "${cmd}" = "up" ]]; then
    docker-compose build;
    docker-compose -f docker-compose.yml -p buzzingpixel up -d;
    exit 0;
fi

if [[ "${cmd}" = "down" ]]; then
    docker kill buzzingpixel-utility;
    docker-compose -f docker-compose.yml -p buzzingpixel down;
    exit 0;
fi

if [[ "${cmd}" = "provision" ]]; then
    docker build -t buzzingpixel:php-dev docker/php-dev;
    docker run -it -v ${PWD}:/app -v buzzingpixel_composer-home-volume:/composer-home-volume --env COMPOSER_HOME=/composer-home-volume -w /app ${composerDockerImage} bash -c "composer install";
    docker run -it -v ${PWD}:/app -v buzzingpixel_node-modules-volume:/app/node_modules -v buzzingpixel_yarn-cache-volume:/usr/local/share/.cache/yarn -w /app ${nodeDockerImage} bash -c "yarn";
    docker run -it -v ${PWD}:/app -v buzzingpixel_node-modules-volume:/app/node_modules -v buzzingpixel_yarn-cache-volume:/usr/local/share/.cache/yarn -w /app ${nodeDockerImage} bash -c "yarn run fab --build-only";
    (cd platform && yarn && cd ..)
    exit 0;
fi

if [[ "${cmd}" = "login" ]]; then
    docker exec -it --user root --workdir /opt/project buzzingpixel-${secondArg} bash;
    exit 0;
fi

if [[ "${cmd}" = "cli" ]]; then
    docker exec -it --user root --workdir /opt/project buzzingpixel-php bash -c "php cli ${allArgsExceptFirst}";
    exit 0;
fi

if [[ "${cmd}" = "yarn" ]]; then
    docker run -it -p 3000:3000 -p 3001:3001 -v ${PWD}:/app -v buzzingpixel_node-modules-volume:/app/node_modules -v buzzingpixel_yarn-cache-volume:/usr/local/share/.cache/yarn -w /app --network=buzzingpixel_common-buzzingpixel-network ${nodeDockerImage} bash -c "${allArgs}";
    exit 0;
fi

if [[ "${cmd}" = "composer" ]]; then
    docker run -it -v ${PWD}:/app -v buzzingpixel_composer-home-volume:/composer-home-volume --env COMPOSER_HOME=/composer-home-volume -w /app ${composerDockerImage} bash -c "${allArgs}";
    exit 0;
fi

if [[ "${cmd}" = "phpcs" ]]; then
    docker run -it -v ${PWD}:/app -w /app buzzingpixel:php-dev bash -c "vendor/bin/phpcs --config-set installed_paths ../../doctrine/coding-standard/lib,../../slevomat/coding-standard; vendor/bin/phpcs src web/index.php bootstrap.php devMode.php config; vendor/bin/php-cs-fixer fix --verbose --dry-run --using-cache=no;";
    exit 0;
fi

if [[ "${cmd}" = "psalm" ]]; then
    docker run -it -v ${PWD}:/app -w /app buzzingpixel:php-dev bash -c "chmod +x /app/vendor/bin/psalm && /app/vendor/bin/psalm";
    exit 0;
fi

if [[ "${cmd}" = "phpstan" ]]; then
    docker run -it -v ${PWD}:/app -w /app buzzingpixel:php-dev bash -c "chmod +x /app/vendor/bin/phpstan && /app/vendor/bin/phpstan analyse config public/index.php src tests cli";
    exit 0;
fi

if [[ "${cmd}" = "phpunit" ]]; then
    docker run -it -v ${PWD}:/app -w /app buzzingpixel:php-dev bash -c "chmod +x /app/vendor/bin/phpunit && /app/vendor/bin/phpunit --configuration /app/phpunit.xml ${allArgsExceptFirst}";
    exit 0;
fi

if [[ "${cmd}" = "eslint" ]]; then
    docker run -it -v ${PWD}:/app -v buzzingpixel_node-modules-volume:/app/node_modules -v buzzingpixel_yarn-cache-volume:/usr/local/share/.cache/yarn -w /app ${nodeDockerImage} bash -c "node_modules/.bin/eslint assetsSource/js/*";
    exit 0;
fi

if [[ "${cmd}" = "cypress" ]]; then
    docker run -it -v ${PWD}:/e2e -w /e2e -e CYPRESS_baseUrl=https://buzzingpixel.localtest.me:26087/ --network=host ${cypressDockerImage};
    exit 0;
fi

if [[ "${cmd}" = "cypress-interactive" ]]; then
    ./platform/node_modules/.bin/cypress open
    exit 0;
fi

printf "${Red}Specified command not found${Reset}\n";
exit 1;
